In [51]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [52]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [53]:
df.shape

(569, 33)

In [54]:
df.drop(['id','Unnamed: 32'],inplace=True,axis=1)

In [55]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [56]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size = 0.2)

In [57]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [58]:
X_train

array([[-0.66504802, -0.48412171, -0.69168423, ..., -0.92228054,
        -0.19785905, -0.12794262],
       [-0.67643194, -0.27014644, -0.70243094, ..., -0.64635407,
        -1.49169619, -0.79748901],
       [ 2.60498317,  1.80395471,  2.76544697, ...,  2.43869963,
         0.47894215,  0.22792739],
       ...,
       [ 0.43350032,  0.96021133,  0.75250711, ...,  2.02419812,
         0.60654906,  1.02072361],
       [-1.30055538, -0.81237922, -1.31375292, ..., -0.63687101,
        -0.23339515, -0.0962974 ],
       [-0.08162209,  0.08485797, -0.1369891 , ..., -0.84060386,
        -0.62752282, -0.79970973]])

In [59]:
y_train

399    B
297    M
202    M
5      M
517    M
      ..
18     M
491    B
258    M
234    B
438    B
Name: diagnosis, Length: 455, dtype: object

In [60]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [61]:
y_train

array([0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0])

# Numpy arrays to Pytorch Tensors

In [62]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [63]:
X_train_tensor.shape

torch.Size([455, 30])

In [64]:
y_train_tensor.shape

torch.Size([455])

# Defining the Model

In [65]:
import torch.nn as nn

class MyNN(nn.Module):

  def __init__(self, num):
    super().__init__()
    self.linear = nn.Linear(num,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

# Important Params

In [66]:
learning_rate = 0.1
epochs = 25

In [67]:
loss_function = nn.BCELoss()

# Training Pipeline

In [69]:
model = MyNN(X_train_tensor.shape[1]) # create model

# Convert tensors to float32 to match model weights dtype
X_train_float = X_train_tensor.float()
y_train_float = y_train_tensor.float()

optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loop

for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_float)

  #calculate loss
  loss = loss_function(y_pred, y_train_float.view(-1,1))

  #clear grad

  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #params update
  optimizer.step()

  #print loss in each epoch
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6099814772605896
Epoch: 2, Loss: 0.4746759831905365
Epoch: 3, Loss: 0.401054322719574
Epoch: 4, Loss: 0.35428541898727417
Epoch: 5, Loss: 0.32148656249046326
Epoch: 6, Loss: 0.2969595193862915
Epoch: 7, Loss: 0.2777760624885559
Epoch: 8, Loss: 0.2622658312320709
Epoch: 9, Loss: 0.2494012415409088
Epoch: 10, Loss: 0.23851311206817627
Epoch: 11, Loss: 0.2291456162929535
Epoch: 12, Loss: 0.22097660601139069
Epoch: 13, Loss: 0.2137717306613922
Epoch: 14, Loss: 0.20735573768615723
Epoch: 15, Loss: 0.2015950232744217
Epoch: 16, Loss: 0.19638553261756897
Epoch: 17, Loss: 0.19164499640464783
Epoch: 18, Loss: 0.18730738759040833
Epoch: 19, Loss: 0.18331900238990784
Epoch: 20, Loss: 0.17963571846485138
Epoch: 21, Loss: 0.1762208342552185
Epoch: 22, Loss: 0.17304351925849915
Epoch: 23, Loss: 0.17007772624492645
Epoch: 24, Loss: 0.16730128228664398
Epoch: 25, Loss: 0.16469505429267883

# Evaluation

In [70]:
with torch.no_grad():
  # Convert inputs to float to match the model weights
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()

  # Convert target to float and match the shape
  y_test_float = y_test_tensor.float().view(-1, 1)

  accuracy = (y_pred == y_test_float).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.9736841917037964