In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [5]:
df.drop(['id','Unnamed: 32'],axis = 1,inplace = True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [7]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size = 0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.09544922, -1.38965409, -0.15507221, ..., -0.86108087,
        -0.11880041, -0.87350622],
       [ 0.22213109, -0.59540175,  0.28780857, ...,  1.40096443,
         1.12588986,  1.28144445],
       [-1.39521882, -1.48309554, -1.26729739, ..., -0.16564422,
         0.23239173,  2.32650611],
       ...,
       [-0.82010975,  0.14278573, -0.85664896, ..., -1.32543493,
        -0.55329859, -0.41580275],
       [ 0.14417956,  0.95105429,  0.09232149, ...,  0.35655866,
        -0.68397473, -0.85003425],
       [ 0.21924399, -0.53232877,  0.13083287, ..., -0.52196169,
        -0.60556905, -0.85506396]])

In [10]:
y_train

295    B
117    M
504    B
458    B
55     B
      ..
435    M
102    B
522    B
385    M
434    B
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0])

In [13]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

In [17]:
from torch.utils.data import Dataset,DataLoader

class CustomDataset(Dataset):

  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self,idx):
    return self.features[idx], self.labels[idx]

In [18]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [19]:
train_dataset[10]

(tensor([ 0.2597, -0.8664,  0.2380,  0.0946, -0.8732,  0.1195, -0.2872, -0.2696,
          0.2737, -0.5136, -0.6017, -1.2528, -0.2813, -0.4269, -1.0284,  0.3505,
          0.1483, -0.0477, -0.8257, -0.2277,  0.0443, -1.0021,  0.2240, -0.1133,
         -0.7972,  0.7413,  0.3548,  0.3878,  0.0952,  0.0028]),
 tensor(0.))

In [21]:
train_loader = DataLoader(train_dataset,batch_size = 32,shuffle = True)
test_loader = DataLoader(test_dataset,batch_size = 32,shuffle = True)

# Defining the Model

In [26]:
import torch.nn as nn

class MyNN(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

# Params

In [27]:
learning_rate = 0.1
epochs = 25

In [30]:
model = MyNN(X_train_tensor.shape[1])

optimizer = torch.optim.SGD(model.parameters(),lr = learning_rate)

loss_function = nn.BCELoss()

# Training Pipeline

In [32]:
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_features)
    #loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))
    #clear gradients
    optimizer.zero_grad()
    #backward pass
    loss.backward()
    #parameters update
    optimizer.step()

  #print loss in each epoch
  print(f'Epoch: {epoch}, Loss: {loss.item()}')

Epoch: 0, Loss: 0.06784005463123322
Epoch: 1, Loss: 0.06626839935779572
Epoch: 2, Loss: 0.0470128171145916
Epoch: 3, Loss: 0.006359022576361895
Epoch: 4, Loss: 0.08035443723201752
Epoch: 5, Loss: 0.03464508801698685
Epoch: 6, Loss: 0.04951487109065056
Epoch: 7, Loss: 0.014346973970532417
Epoch: 8, Loss: 0.061437178403139114
Epoch: 9, Loss: 0.31943392753601074
Epoch: 10, Loss: 0.06895782798528671
Epoch: 11, Loss: 0.001981823006644845
Epoch: 12, Loss: 0.0645216554403305
Epoch: 13, Loss: 0.07646723836660385
Epoch: 14, Loss: 0.0067528849467635155
Epoch: 15, Loss: 0.003660347778350115
Epoch: 16, Loss: 0.034329112619161606
Epoch: 17, Loss: 0.0038700972218066454
Epoch: 18, Loss: 0.1127476617693901
Epoch: 19, Loss: 0.01709662564098835
Epoch: 20, Loss: 0.019363196566700935
Epoch: 21, Loss: 0.014799507334828377
Epoch: 22, Loss: 0.039819445461034775
Epoch: 23, Loss: 0.056924980133771896
Epoch: 24, Loss: 0.04919511452317238

##Evaluation

In [33]:
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    #foward pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float()

    #calculate accuracy for the current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

#calculate overall accuracy
overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'Overall Accuracy: {overall_accuracy}')

Overall Accuracy: 0.9609375